name: Test Python App

on:
  push:
    branches:
      - dev

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Check Python version
        run: python --version

      - name: Check installed packages
        run: pip list

      - name: Run tests
        run: python -m pytest tests/
